version: '3.9'

services:
  intro:
    build:
      context: .
      args:
        - DEBUG=True
    ports:
      - "8000:8000"
    volumes:
      - ".:/intro"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
