# Generated by Django 4.2.1 on 2023-06-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_comments_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='text',
            new_name='title',
        ),
    ]
