# Generated by Django 4.2.1 on 2023-06-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_type',
            field=models.CharField(choices=[('E', 'Email'), ('P', 'Phone')], default='E', max_length=2),
            preserve_default=False,
        ),
    ]
