# Generated by Django 4.2.1 on 2023-05-28 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('I', 'In Progress'), ('S', 'Solved')], default='O', max_length=155),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='parent',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replieds', to='support.ticket'),
        ),
    ]
