# Generated by Django 4.2.1 on 2023-06-18 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('authority', models.TextField(blank=True, max_length=500, null=True, verbose_name='authority')),
                ('refID', models.TextField(blank=True, max_length=500, null=True, verbose_name='refrence id')),
                ('status', models.CharField(choices=[('S', 'Success'), ('F', 'Failed'), ('P', 'Pending'), ('N', 'Not Paid')], default='N', max_length=2, verbose_name='status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('Transaction'), models.Model),
        ),
    ]
